const AUTH_STATUS_ACTIVE = "AUTH_STATUS_ACTIVE"
const AUTH_STATUS_NOT_ACTIVE ="AUTH_STATUS_NOT_ACTIVE"
const UPDATE_AUTH = "UPDATE_AUTH"
const UPDATED_AUTH = "UPDATED_AUTH"

const INITIAL_FETCH = "INITIAL_FETCH"
export {AUTH_STATUS_ACTIVE, AUTH_STATUS_NOT_ACTIVE, UPDATE_AUTH, UPDATED_AUTH, INITIAL_FETCH}
